-- Apply in Supabase SQL Editor before deploying the frontend.
-- Keeps existing research_areas and research_area_id values so current content survives.
begin;

create table if not exists public.epistemologies (
  id bigint generated by default as identity primary key,
  research_area_id bigint not null references public.research_areas(id),
  name text not null,
  slug text not null,
  description text not null default '',
  unique (research_area_id, slug),
  unique (id, research_area_id)
);

alter table public.researchers add column if not exists epistemology_id bigint;
alter table public.projects add column if not exists epistemology_id bigint;
alter table public.publications add column if not exists epistemology_id bigint;

create table if not exists public.intellectual_properties (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer,
  research_area_id bigint references public.research_areas(id),
  epistemology_id bigint,
  summary text not null default '',
  description text not null default '',
  external_url text not null default '',
  ip_type text not null default '',
  registration_number text not null default '',
  holders text not null default '',
  status text not null default ''
);

create table if not exists public.community_services (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer,
  research_area_id bigint references public.research_areas(id),
  epistemology_id bigint,
  summary text not null default '',
  description text not null default '',
  external_url text not null default '',
  partners text not null default '',
  location text not null default '',
  status text not null default ''
);

-- A selected Epistemology must belong to the same Ontology. Null means unclassified.
do $$
declare table_name text;
begin
  foreach table_name in array array['researchers', 'projects', 'publications', 'intellectual_properties', 'community_services'] loop
    if not exists (select 1 from pg_constraint where conrelid = ('public.' || table_name)::regclass
      and conname = table_name || '_epistemology_requires_ontology') then
      execute format('alter table public.%I add constraint %I check (epistemology_id is null or research_area_id is not null)',
        table_name, table_name || '_epistemology_requires_ontology');
    end if;
    if not exists (select 1 from pg_constraint where conrelid = ('public.' || table_name)::regclass
      and conname = table_name || '_epistemology_ontology_fk') then
      execute format('alter table public.%I add constraint %I foreign key (epistemology_id, research_area_id) references public.epistemologies (id, research_area_id)',
        table_name, table_name || '_epistemology_ontology_fk');
    end if;
  end loop;
end $$;

create table if not exists public.intellectual_property_researchers (
  intellectual_property_id bigint not null references public.intellectual_properties(id) on delete cascade,
  researcher_id bigint not null references public.researchers(id) on delete cascade,
  primary key (intellectual_property_id, researcher_id)
);

create table if not exists public.community_service_researchers (
  community_service_id bigint not null references public.community_services(id) on delete cascade,
  researcher_id bigint not null references public.researchers(id) on delete cascade,
  primary key (community_service_id, researcher_id)
);

-- The existing public.is_admin() function is used by the site's current policies.
alter table public.epistemologies enable row level security;
alter table public.intellectual_properties enable row level security;
alter table public.community_services enable row level security;
alter table public.intellectual_property_researchers enable row level security;
alter table public.community_service_researchers enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['epistemologies', 'intellectual_properties', 'community_services',
    'intellectual_property_researchers', 'community_service_researchers'] loop
    execute format('drop policy if exists public_read on public.%I', table_name);
    execute format('create policy public_read on public.%I for select using (true)', table_name);
    execute format('drop policy if exists admin_insert on public.%I', table_name);
    execute format('create policy admin_insert on public.%I for insert to authenticated with check (public.is_admin())', table_name);
    execute format('drop policy if exists admin_update on public.%I', table_name);
    execute format('create policy admin_update on public.%I for update to authenticated using (public.is_admin()) with check (public.is_admin())', table_name);
    execute format('drop policy if exists admin_delete on public.%I', table_name);
    execute format('create policy admin_delete on public.%I for delete to authenticated using (public.is_admin())', table_name);
  end loop;
end $$;

grant select on public.epistemologies, public.intellectual_properties, public.community_services,
  public.intellectual_property_researchers, public.community_service_researchers to anon, authenticated;
grant insert, update, delete on public.epistemologies, public.intellectual_properties, public.community_services,
  public.intellectual_property_researchers, public.community_service_researchers to authenticated;
grant usage, select on sequence public.epistemologies_id_seq, public.intellectual_properties_id_seq,
  public.community_services_id_seq to authenticated;

commit;
